stateDiagram-v2
    [*] --> PETIT_RXTX_RX
    PETIT_RXTX_RX --> PETIT_RXTX_RX: Message not ready
    PETIT_RXTX_RX --> PETIT_RXTX_PROCESS: Message Ready
    PETIT_RXTX_PROCESS --> PETIT_RXTX_TX_DATABUF
    PETIT_RXTX_TX_DATABUF --> PETIT_RXTX_TX_DLY
    PETIT_RXTX_TX_DLY --> PETIT_RXTX_TX
    PETIT_RXTX_TX --> PETIT_RXTX_RX
